/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.attendance;

import includes.MysqlConnection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kavindu
 */
public class StudentSelector extends javax.swing.JDialog {

    private int subjectId;
    
    private AttendancePanel attendancePanel;

    /**
     * Creates new form StudentSelector
     */
    public StudentSelector(java.awt.Frame parent, boolean modal, int subjectId, AttendancePanel attendancePanel) {
        super(parent, modal);
        initComponents();
        this.subjectId = subjectId;
        this.attendancePanel = attendancePanel;
        loadStudentsTableData();
    }

    private void loadStudentsTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) studentsTable.getModel();
        tableModel.setRowCount(0);
        try {
            ResultSet entrollmentResultSet = MysqlConnection.executeSearch("SELECT * FROM `student_subject_entrollments` WHERE `subject_id`='" + subjectId + "' ");
            while (entrollmentResultSet.next()) {
                Vector vector = new Vector();
                ResultSet studentResultSet = MysqlConnection.executeSearch("SELECT * FROM `students` WHERE `id`='" + entrollmentResultSet.getInt("student_id") + "' ");
                if (studentResultSet.next()) {
                    vector.add(studentResultSet.getString("id"));
                    vector.add(studentResultSet.getString("name"));
                }
                tableModel.addRow(vector);
            }
            studentsTable.setModel(tableModel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("student selctor");
        setResizable(false);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsTableMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int row = studentsTable.getSelectedRow();
            
            String studentIdString = String.valueOf(studentsTable.getValueAt(row, 0));
            attendancePanel.storeUser(Integer.parseInt(studentIdString));
            dispose();
        }
    }//GEN-LAST:event_studentsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentsTable;
    // End of variables declaration//GEN-END:variables
}
