/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.payments;

import includes.MysqlConnection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author kavindu
 */
public class CreatePaymentDialog extends javax.swing.JDialog {

    private PaymentPanel paymentPanel;

    /**
     * Creates new form CreatePaymentDialog
     */
    public CreatePaymentDialog(java.awt.Frame parent, boolean modal, PaymentPanel paymentPanel) {
        super(parent, modal);
        initComponents();
        this.paymentPanel = paymentPanel;
        loadSubjectTableData();
    }

    private void loadSubjectTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) subjectsTable.getModel();
        tableModel.setRowCount(0);

        try {
            ResultSet subjectsResultSet = MysqlConnection.executeSearch("SELECT * FROM `subjects` ");
            while (subjectsResultSet.next()) {
                Vector vector = new Vector();
                vector.add(subjectsResultSet.getString("id"));
                vector.add(subjectsResultSet.getString("name"));

                tableModel.addRow(vector);
            }

            subjectsTable.setModel(tableModel);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadStudentsTableData(String subjectId) {
        DefaultTableModel tableModel = (DefaultTableModel) studentsTable.getModel();
        tableModel.setRowCount(0);

        try {
            ResultSet studentsSubjectEntrollmentResultSet = MysqlConnection.executeSearch("SELECT * FROM `student_subject_entrollments` WHERE `subject_id`='" + subjectId + "' ");
            while (studentsSubjectEntrollmentResultSet.next()) {
                ResultSet studentResultSet = MysqlConnection.executeSearch("SELECT * FROM `students` WHERE `id`='" + studentsSubjectEntrollmentResultSet.getString("student_id") + "' ");
                if (studentResultSet.next()) {
                    Vector vector = new Vector();
                    vector.add(studentResultSet.getString("id"));
                    vector.add(studentResultSet.getString("name"));

                    tableModel.addRow(vector);
                }
                studentsTable.setModel(tableModel);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subjectsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("create payment");
        setResizable(false);

        subjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subjectsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjectsTable);

        jLabel1.setText("subjects");

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentsTable);

        jLabel2.setText("students");

        jLabel3.setText("price");

        createButton.setText("create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(38, 38, 38)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String price = priceField.getText();

        int subjectRow = subjectsTable.getSelectedRow();
        int studentRow = studentsTable.getSelectedRow();

        if (subjectRow > -1 && studentRow > -1 && !price.isEmpty()) {
            Double priceDouble = Double.parseDouble(price);
            try {
                String subjctIdString = String.valueOf(subjectsTable.getValueAt(subjectRow, 0));
                String studentIdString = String.valueOf(studentsTable.getValueAt(studentRow, 0));
                paymentPanel.storeData(studentIdString, subjctIdString, priceDouble);
                dispose();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please select at least one field!");
        }

    }//GEN-LAST:event_createButtonActionPerformed

    private void getDateId() {
        try {
            ResultSet dateResultSet = MysqlConnection.executeSearch("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void subjectsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectsTableMouseClicked
        // TODO add your handling code here:
        int row = subjectsTable.getSelectedRow();

        if (row > -1) {
            String subjectId = String.valueOf(subjectsTable.getValueAt(row, 0));
            loadStudentsTableData(subjectId);
        }

    }//GEN-LAST:event_subjectsTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceField;
    private javax.swing.JTable studentsTable;
    private javax.swing.JTable subjectsTable;
    // End of variables declaration//GEN-END:variables
}
