/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.studentSubjectEntrollment;

import includes.MysqlConnection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kavindu
 */
public class AddEntrollment extends javax.swing.JDialog {

    private Runnable successAction;

    /**
     * Creates new form AddEntrollment
     */
    public AddEntrollment(java.awt.Frame parent, boolean modal, Runnable successAction) {
        super(parent, modal);
        initComponents();
        this.successAction = successAction;
        loadStudentsTableData();
        loadSubjectsTableData();
    }

    private void loadStudentsTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) studentsTable.getModel();
        tableModel.setRowCount(0);
        try {
            ResultSet studentsResultSet = MysqlConnection.executeSearch("SELECT * FROM `students`");
            while (studentsResultSet.next()) {
                Vector vector = new Vector();
                vector.add(studentsResultSet.getString("id"));
                vector.add(studentsResultSet.getString("name"));
                tableModel.addRow(vector);
            }
            studentsTable.setModel(tableModel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadSubjectsTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) subjectsTable.getModel();
        tableModel.setRowCount(0);
        try {
            ResultSet studentsResultSet = MysqlConnection.executeSearch("SELECT * FROM `subjects`");
            while (studentsResultSet.next()) {
                Vector vector = new Vector();
                vector.add(studentsResultSet.getString("id"));
                vector.add(studentsResultSet.getString("name"));
                tableModel.addRow(vector);
            }
            subjectsTable.setModel(tableModel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void store() {
        // TODO add your handling code here:
        int studentTableRow = studentsTable.getSelectedRow();
        int subjectsTableRow = subjectsTable.getSelectedRow();

        if (studentTableRow > -1 && subjectsTableRow > -1) {
            int studentId = Integer.parseInt(String.valueOf(studentsTable.getValueAt(studentTableRow, 0)));
            int subjectId = Integer.parseInt(String.valueOf(subjectsTable.getValueAt(subjectsTableRow, 0)));
            try {
                ResultSet checkResultSet = MysqlConnection.executeSearch("SELECT * FROM `student_subject_entrollments` WHERE `student_id`='" + studentId + "' AND `subject_id`='" + subjectId + "' ");
                if (!checkResultSet.next()) {
                    MysqlConnection.executeIUD("INSERT INTO `student_subject_entrollments`(`student_id`, `subject_id`) VALUES ('" + studentId + "', '" + subjectId + "') ");
                    JOptionPane.showMessageDialog(this, "Registered !");
                    successAction.run();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Already Exists");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "You need to select at least one row");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subjectsTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add entrollment");
        setResizable(false);

        jLabel1.setText("Student");

        jLabel2.setText("Subjects");

        subjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(subjectsTable);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentsTable);

        createButton.setText("create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(213, 213, 213)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(createButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        store();
    }//GEN-LAST:event_createButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable studentsTable;
    private javax.swing.JTable subjectsTable;
    // End of variables declaration//GEN-END:variables
}
