/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.studentSubjectEntrollment;

import includes.MysqlConnection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kavindu
 */
public class StudentSubjectEntrollment extends javax.swing.JPanel {

    /**
     * Creates new form StudentSubjectEntrollment
     */
    public StudentSubjectEntrollment() {
        initComponents();
        loadTableData();
    }

    private void loadTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) entrollmentsTable.getModel();
        tableModel.setRowCount(0);
        try {
            String searchString = searchField.getText();
            ResultSet studentsResultSet = MysqlConnection.executeSearch("SELECT * FROM `student_subject_entrollments` INNER JOIN `students` ON `student_subject_entrollments`.`student_id`=`students`.`id` INNER JOIN `subjects` ON `student_subject_entrollments`.`subject_id`=`subjects`.`id` WHERE `students`.`name` LIKE '%"+searchString+"%' OR `subjects`.`name` LIKE '%"+searchString+"%' ");
            while (studentsResultSet.next()) {
                Vector vector = new Vector();
                vector.add(studentsResultSet.getString("id"));
                vector.add(studentsResultSet.getString("students.name"));
                vector.add(studentsResultSet.getString("subjects.name"));
                tableModel.addRow(vector);
            }
            entrollmentsTable.setModel(tableModel);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entrollmentsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();

        entrollmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "student", "subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        entrollmentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrollmentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(entrollmentsTable);

        jButton1.setText("add new");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Students Entrollments");

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AddEntrollment(null, true, () -> {
            loadTableData();
        }).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entrollmentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrollmentsTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = entrollmentsTable.getSelectedRow();
            int id = Integer.parseInt(String.valueOf(entrollmentsTable.getValueAt(row, 0)));
            new UpdateEntrollment(null, true, id, () -> {
                loadTableData();
            }).setVisible(true);
        }
    }//GEN-LAST:event_entrollmentsTableMouseClicked

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        loadTableData();
    }//GEN-LAST:event_searchFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable entrollmentsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
